{{- if .Values.certificate.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
spec:
  secretName: {{ include "freeradius.fullname" . }}-cert-secret
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    {{- .Values.certificate.dnsNames | toYaml | nindent 4}}
  issuerRef:
    {{- .Values.certificate.issuerRef | toYaml | nindent 4}}
{{- end -}}
