---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freeradius.fullname" . }}-etc-freeradius
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
