apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: radius
      protocol: UDP
      name: radius
  selector:
    {{- include "freeradius.selectorLabels" . | nindent 4 }}
