apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-meta.fullname" . }}
  labels:
    {{- include "mautrix-meta.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- fromYaml .Values.config | toYaml | nindent 4 }}
  registration.yaml: ""
