apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-meta.fullname" . }}-appservice-nocollide
  labels:
    {{- include "mautrix-meta.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: appservice
      protocol: TCP
      name: appservice
  selector:
    {{- include "mautrix-meta.selectorLabels" . | nindent 4 }}
